version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing tools..."
      - apt-get update && apt-get install -y jq curl bc
      - mvn -version
      - java -version

  pre_build:
    commands:
      - echo "Pre-build phase"

  build:
    commands:
      - echo "Running Maven tests..."
      - mvn clean test || true

  post_build:
    commands:
      - echo "Generating Allure report..."
      - mvn allure:report || true

      - echo "Sending Slack notification..."
      - |
        SUMMARY_FILE="target/site/allure-maven-plugin/widgets/summary.json"
        if [ -f $SUMMARY_FILE ]; then
          FAILED=$(jq '.statistic.failed' $SUMMARY_FILE)
          BROKEN=$(jq '.statistic.broken' $SUMMARY_FILE)
          SKIPPED=$(jq '.statistic.skipped' $SUMMARY_FILE)
          PASSED=$(jq '.statistic.passed' $SUMMARY_FILE)
          UNKNOWN=$(jq '.statistic.unknown' $SUMMARY_FILE)
          TOTAL=$(jq '.statistic.total' $SUMMARY_FILE)
          START_TIME=$(jq '.time.start' $SUMMARY_FILE)
          STOP_TIME=$(jq '.time.stop' $SUMMARY_FILE)
          DURATION_MS=$(jq '.time.duration' $SUMMARY_FILE)
          DURATION_MIN=$(echo "scale=2; $DURATION_MS / 60000" | bc)
          START_TIME_HUMAN=$(date -d @$((START_TIME / 1000)) +"%Y-%m-%d %H:%M:%S")
          STOP_TIME_HUMAN=$(date -d @$((STOP_TIME / 1000)) +"%Y-%m-%d %H:%M:%S")
        
          MESSAGE="*Test Summary*\\n:white_check_mark: Passed: $PASSED\\n:x: Failed: $FAILED\\n:warning: Broken: $BROKEN\\n:arrow_double_down: Skipped: $SKIPPED\\n:grey_question: Unknown: $UNKNOWN\\n🧮 Total: $TOTAL\\n⏱ Start: $START_TIME_HUMAN\\n⏱ End: $STOP_TIME_HUMAN\\n🕒 Duration: ${DURATION_MIN} min"
        
        curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
        else
          echo "Allure summary.json not found. Skipping Slack notification."
        fi

      - echo "Sending Zephyr report..."
      - CURRENT_DATE=$(date +"%Y/%m/%d")
      - |
        echo "Fetching current Jira Sprint..."
        SPRINT_VALUE=$(curl -u $JIRA_USER:$JIRA_TOKEN -X GET \
          -H "Content-Type: application/json" \
          "https://aholguin.atlassian.net/rest/agile/1.0/board/1/sprint?state=active" | jq -r '.values[0].name')

        echo "Current Sprint: $SPRINT_VALUE"

        echo "{
          \"name\": \"Healthedly CRM - $SPRINT_VALUE - API Demo Tests - $CURRENT_DATE\",
          \"description\": \"Healthedly CRM API Automated Tests\",
          \"jiraProjectVersion\": 10000,
          \"folderId\": 21640948
        }" > test_cycle_zephyr.json

      - XML_FILE="target/surefire-reports/TEST-TestSuite.xml"
      - |
        if [ -f "$XML_FILE" ]; then
          echo "Sending XML file to Zephyr..."
          curl -X POST \
            -H "Authorization: Bearer $ZEPHYR_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@${XML_FILE};type=application/xml" \
            -F "testCycle=@test_cycle_zephyr.json;type=application/json" \
            "https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey=SCRUM&autoCreateTestCases=false"
        else
          echo "XML file for Zephyr not found."
        fi

artifacts:
  secondary-artifacts:
    allureReport:
      base-directory: target/site/allure-maven-plugin
      files:
        - '**/*'
    junitResults:
      base-directory: target/surefire-reports
      files:
        - '**/*'
  files:
    - test_cycle_zephyr.json
